# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-09 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('avg_rating', models.PositiveIntegerField(default=0)),
                ('num_review', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=50)),
                ('rating', models.PositiveIntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('review_date', models.DateField()),
            ],
        ),
    ]
